# Directories to backup: paths without spaces in their name
BACKUP_INPUT: /data/input
BACKUP_OUTPUT: /data/backup

# Run backup at 4:00am
BACKUP_CRON_EXP: 0 4 * * *

# Delete backups that are over 15 days
BACKUP_TTL: 15

# Owner Info
BACKUP_FILE_OWNER_ID: 0
BACKUP_FILE_GROUP_ID: 0
BACKUP_FILE_PERMISSIONS: 600
