#!/bin/bash -e

# Usage: /sbin/backup

source /container/run/environment.sh

# BACKUP_PRE_SCRIPT is a path to a script that will be executed before the backup
if [ -n "$BACKUP_PRE_SCRIPT" ] && [ -f "$BACKUP_PRE_SCRIPT" ]; then
  $BACKUP_PRE_SCRIPT
fi

# delete backups that are over $MMC_MAIL_BACKUP_TTL days
find $BACKUP_OUTPUT -type f -mtime +$BACKUP_TTL -exec rm {} \;

# Date format for the dump file name
dateFileFormat="+%Y%m%dT%H%M%S"
backupFilePath="$BACKUP_OUTPUT/$(date "$dateFileFormat").tar.gz"

tar -czf $backupFilePath $BACKUP_INPUT
chmod $BACKUP_FILE_PERMISSIONS $backupFilePath
chown $BACKUP_FILE_OWNER_ID:$BACKUP_FILE_GROUP_ID $backupFilePath

exit 0
